# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\david\Desktop\guiiqt5\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(933, 683)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("\n"
"\n"
"background-color: rgb(255, 255, 127);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: #000000ff;\n"
"    border-radius:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(53, 53, 79);\n"
"    border-radius:20px\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 5)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_superior)
        self.label.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(653, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_minimizar.setStyleSheet("")
        self.bt_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\minimizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimizar.setIcon(icon)
        self.bt_minimizar.setIconSize(QtCore.QSize(38, 38))
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_restaurar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_restaurar.setStyleSheet("")
        self.bt_restaurar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\restaurar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_restaurar.setIcon(icon1)
        self.bt_restaurar.setIconSize(QtCore.QSize(38, 38))
        self.bt_restaurar.setObjectName("bt_restaurar")
        self.horizontalLayout.addWidget(self.bt_restaurar)
        self.bt_maximizar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_maximizar.setStyleSheet("")
        self.bt_maximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\maximizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maximizar.setIcon(icon2)
        self.bt_maximizar.setIconSize(QtCore.QSize(30, 30))
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar.setStyleSheet("")
        self.bt_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cerrar.setIcon(icon3)
        self.bt_cerrar.setIconSize(QtCore.QSize(38, 38))
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout.addWidget(self.bt_cerrar)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(self.frame)
        self.frame_inferior.setStyleSheet("QFrame{\n"
"background-color: rgb(53, 53, 79);\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 87 12pt \"Arial Black\";\n"
"    background-color: #000000ff;\n"
"    border-radius:5px;\n"
"    color: rgb(20,200,220);\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: black;\n"
"}")
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menu_lateral = QtWidgets.QFrame(self.frame_inferior)
        self.menu_lateral.setMinimumSize(QtCore.QSize(0, 0))
        self.menu_lateral.setMaximumSize(QtCore.QSize(300, 16777215))
        self.menu_lateral.setStyleSheet("QFrame{\n"
"background-color: rgb(53, 53, 79);\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 87 12pt \"Arial Black\";\n"
"    background-color: #000000ff;\n"
"    border-radius:5px;\n"
"    color: rgb(20,200,220);\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: black;\n"
"}")
        self.menu_lateral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_lateral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_lateral.setObjectName("menu_lateral")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu_lateral)
        self.verticalLayout_4.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_caltech = QtWidgets.QFrame(self.menu_lateral)
        self.frame_caltech.setMaximumSize(QtCore.QSize(16777215, 177))
        self.frame_caltech.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_caltech.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_caltech.setObjectName("frame_caltech")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_caltech)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_3 = QtWidgets.QLabel(self.frame_caltech)
        self.label_3.setMaximumSize(QtCore.QSize(255, 16777215))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\Corrección Logopng_Mesa de trabajo 1 copia.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_16.addWidget(self.label_3)
        self.verticalLayout_4.addWidget(self.frame_caltech)
        self.bt_1 = QtWidgets.QPushButton(self.menu_lateral)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\chip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_1.setIcon(icon4)
        self.bt_1.setIconSize(QtCore.QSize(40, 40))
        self.bt_1.setObjectName("bt_1")
        self.verticalLayout_4.addWidget(self.bt_1)
        self.frame_2 = QtWidgets.QFrame(self.menu_lateral)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.bt_2 = QtWidgets.QPushButton(self.frame_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\base-de-datos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_2.setIcon(icon5)
        self.bt_2.setIconSize(QtCore.QSize(40, 40))
        self.bt_2.setObjectName("bt_2")
        self.verticalLayout_15.addWidget(self.bt_2)
        self.bt_3 = QtWidgets.QPushButton(self.frame_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\moto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_3.setIcon(icon6)
        self.bt_3.setIconSize(QtCore.QSize(40, 40))
        self.bt_3.setObjectName("bt_3")
        self.verticalLayout_15.addWidget(self.bt_3)
        self.bt_4 = QtWidgets.QPushButton(self.frame_2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\archivo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_4.setIcon(icon7)
        self.bt_4.setIconSize(QtCore.QSize(32, 40))
        self.bt_4.setObjectName("bt_4")
        self.verticalLayout_15.addWidget(self.bt_4)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.horizontalLayout_2.addWidget(self.menu_lateral)
        self.frame_4 = QtWidgets.QFrame(self.frame_inferior)
        self.frame_4.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_6.setStyleSheet("QFrame{\n"
"background-color: rgb(53, 53, 79);\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 87 12pt \"Arial Black\";\n"
"    background-color: #000000ff;\n"
"    border-radius:5px;\n"
"    color: rgb(20,200,220);\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: black;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bt_menu_1 = QtWidgets.QPushButton(self.frame_6)
        self.bt_menu_1.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\izquierda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_menu_1.setIcon(icon8)
        self.bt_menu_1.setIconSize(QtCore.QSize(40, 40))
        self.bt_menu_1.setObjectName("bt_menu_1")
        self.horizontalLayout_3.addWidget(self.bt_menu_1)
        self.bt_menu_2 = QtWidgets.QPushButton(self.frame_6)
        self.bt_menu_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\derecha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_menu_2.setIcon(icon9)
        self.bt_menu_2.setIconSize(QtCore.QSize(40, 40))
        self.bt_menu_2.setObjectName("bt_menu_2")
        self.horizontalLayout_3.addWidget(self.bt_menu_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setStyleSheet("\n"
"QLineEdit{\n"
"    font: 75 12pt \"Times New Roman\";\n"
"    background-color: rgb(0,0,0);\n"
"    border-radius:8px;\n"
"    color: rgb(255,255,255);\n"
"    border: 2px solid #14c8dc;\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_11.setStyleSheet("QFrame{\n"
"background-color: rgb(53, 53, 79);\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 87 12pt \"Arial Black\";\n"
"    background-color: #000000ff;\n"
"    border-radius:5px;\n"
"    color: rgb(20,200,220);\n"
"    border: 0px solid white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: black;\n"
"}")
        self.pushButton_11.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon10)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setStyleSheet("QPushButton{\n"
"    font: 87 12pt \"Arial Black\";\n"
"    background-color: #000000ff;\n"
"    border-radius:5px;\n"
"    color: rgb(20,200,220);\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: black;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget_2.setStyleSheet("QLabel{\n"
"    background-color: rgb(255, 255, 127);\n"
"    font: 11pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: black;\n"
"}")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_uno = QtWidgets.QWidget()
        self.page_uno.setObjectName("page_uno")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_uno)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_8 = QtWidgets.QFrame(self.page_uno)
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_16 = QtWidgets.QLabel(self.frame_8)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_21.addWidget(self.label_16)
        self.label_18 = QtWidgets.QLabel(self.frame_8)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_21.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.frame_8)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_21.addWidget(self.label_19)
        self.verticalLayout_20.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.page_uno)
        self.frame_9.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.pasos_excel = QtWidgets.QLineEdit(self.frame_9)
        self.pasos_excel.setGeometry(QtCore.QRect(10, 50, 241, 22))
        self.pasos_excel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pasos_excel.setText("")
        self.pasos_excel.setObjectName("pasos_excel")
        self.bt_aceptar_manual = QtWidgets.QPushButton(self.frame_9)
        self.bt_aceptar_manual.setGeometry(QtCore.QRect(20, 130, 231, 91))
        self.bt_aceptar_manual.setStyleSheet("QPushButton{\n"
"    font: 87 12pt \"Arial Black\";\n"
"    background-color: #000000ff;\n"
"    border-radius:5px;\n"
"\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: black;\n"
"}")
        self.bt_aceptar_manual.setObjectName("bt_aceptar_manual")
        self.verticalLayout_20.addWidget(self.frame_9)
        self.stackedWidget_2.addWidget(self.page_uno)
        self.page_dos = QtWidgets.QWidget()
        self.page_dos.setObjectName("page_dos")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_dos)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.bt_rutina1 = QtWidgets.QPushButton(self.page_dos)
        self.bt_rutina1.setMinimumSize(QtCore.QSize(0, 70))
        self.bt_rutina1.setObjectName("bt_rutina1")
        self.verticalLayout_11.addWidget(self.bt_rutina1)
        self.bt_rutina2 = QtWidgets.QPushButton(self.page_dos)
        self.bt_rutina2.setObjectName("bt_rutina2")
        self.verticalLayout_11.addWidget(self.bt_rutina2)
        self.bt_rutina3 = QtWidgets.QPushButton(self.page_dos)
        self.bt_rutina3.setObjectName("bt_rutina3")
        self.verticalLayout_11.addWidget(self.bt_rutina3)
        self.bt_rutina4 = QtWidgets.QPushButton(self.page_dos)
        self.bt_rutina4.setObjectName("bt_rutina4")
        self.verticalLayout_11.addWidget(self.bt_rutina4)
        self.bt_rutina5 = QtWidgets.QPushButton(self.page_dos)
        self.bt_rutina5.setObjectName("bt_rutina5")
        self.verticalLayout_11.addWidget(self.bt_rutina5)
        self.stackedWidget_2.addWidget(self.page_dos)
        self.page_tres = QtWidgets.QWidget()
        self.page_tres.setObjectName("page_tres")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_tres)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.bt_angulo0 = QtWidgets.QPushButton(self.page_tres)
        self.bt_angulo0.setObjectName("bt_angulo0")
        self.verticalLayout_13.addWidget(self.bt_angulo0)
        self.bt_rpm0 = QtWidgets.QPushButton(self.page_tres)
        self.bt_rpm0.setObjectName("bt_rpm0")
        self.verticalLayout_13.addWidget(self.bt_rpm0)
        self.bt_tiempo0 = QtWidgets.QPushButton(self.page_tres)
        self.bt_tiempo0.setObjectName("bt_tiempo0")
        self.verticalLayout_13.addWidget(self.bt_tiempo0)
        self.stackedWidget_2.addWidget(self.page_tres)
        self.page_cuatro = QtWidgets.QWidget()
        self.page_cuatro.setObjectName("page_cuatro")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_cuatro)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.page_cuatro)
        self.label_15.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_12.addWidget(self.label_15)
        self.label_6 = QtWidgets.QLabel(self.page_cuatro)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.page_cuatro)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"text-decoration: underline;\n"
"font: 12pt \"Arial\";\n"
"")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_12.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.page_cuatro)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 11pt \"Arial\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.page_cuatro)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.page_cuatro)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_12.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.page_cuatro)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.page_cuatro)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.page_cuatro)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.label_14 = QtWidgets.QLabel(self.page_cuatro)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.stackedWidget_2.addWidget(self.page_cuatro)
        self.verticalLayout_6.addWidget(self.stackedWidget_2)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_paginas = QtWidgets.QFrame(self.frame_inferior)
        self.frame_paginas.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_paginas.setStyleSheet("QFrame{\n"
"    background-color: rgb(53, 53, 79);\n"
"}\n"
"QLabel{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color: rgb(20,200,220);\n"
"border:0px solid #14c8dc;\n"
"}")
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_paginas)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_paginas)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setStyleSheet("QFrame{\n"
"    background-color: rgb(170, 255, 0);\n"
"}\n"
"QLabel{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_17.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.page)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_17.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.page)
        self.page_rutina1 = QtWidgets.QWidget()
        self.page_rutina1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page_rutina1.setObjectName("page_rutina1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_rutina1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2_ruitna1 = QtWidgets.QFrame(self.page_rutina1)
        self.frame_2_ruitna1.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_2_ruitna1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_ruitna1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_ruitna1.setObjectName("frame_2_ruitna1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2_ruitna1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.frame_2_ruitna1)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.label_17 = QtWidgets.QLabel(self.frame_2_ruitna1)
        self.label_17.setMinimumSize(QtCore.QSize(0, 40))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_5.addWidget(self.frame_2_ruitna1)
        self.frame_3_ruitna1 = QtWidgets.QFrame(self.page_rutina1)
        self.frame_3_ruitna1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3_ruitna1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3_ruitna1.setObjectName("frame_3_ruitna1")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_3_ruitna1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.txt_tiempo = QtWidgets.QLineEdit(self.frame_3_ruitna1)
        self.txt_tiempo.setObjectName("txt_tiempo")
        self.verticalLayout_14.addWidget(self.txt_tiempo)
        self.bt_aceptar_R1 = QtWidgets.QPushButton(self.frame_3_ruitna1)
        self.bt_aceptar_R1.setObjectName("bt_aceptar_R1")
        self.verticalLayout_14.addWidget(self.bt_aceptar_R1)
        self.label_cuenta_regresiva = QtWidgets.QLabel(self.frame_3_ruitna1)
        self.label_cuenta_regresiva.setText("")
        self.label_cuenta_regresiva.setObjectName("label_cuenta_regresiva")
        self.verticalLayout_14.addWidget(self.label_cuenta_regresiva)
        self.bt_detener_R1 = QtWidgets.QPushButton(self.frame_3_ruitna1)
        self.bt_detener_R1.setObjectName("bt_detener_R1")
        self.verticalLayout_14.addWidget(self.bt_detener_R1)
        self.horizontalLayout_5.addWidget(self.frame_3_ruitna1)
        self.stackedWidget.addWidget(self.page_rutina1)
        self.page_rutina2 = QtWidgets.QWidget()
        self.page_rutina2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page_rutina2.setObjectName("page_rutina2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_rutina2)
        self.verticalLayout_8.setContentsMargins(2, 2, 2, 0)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stackedWidget.addWidget(self.page_rutina2)
        self.page_rutina3 = QtWidgets.QWidget()
        self.page_rutina3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page_rutina3.setObjectName("page_rutina3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_rutina3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.page_rutina3)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\moto.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.stackedWidget.addWidget(self.page_rutina3)
        self.page_rutina4 = QtWidgets.QWidget()
        self.page_rutina4.setEnabled(True)
        self.page_rutina4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page_rutina4.setObjectName("page_rutina4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_rutina4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.page_rutina4)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("c:\\Users\\david\\Desktop\\guiiqt5\\archivo.png"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.stackedWidget.addWidget(self.page_rutina4)
        self.page_rutina5 = QtWidgets.QWidget()
        self.page_rutina5.setObjectName("page_rutina5")
        self.stackedWidget.addWidget(self.page_rutina5)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_paginas)
        self.verticalLayout_2.addWidget(self.frame_inferior)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Menu Glad"))
        self.bt_1.setText(_translate("MainWindow", "Manual"))
        self.bt_2.setText(_translate("MainWindow", "Rutinas"))
        self.bt_3.setText(_translate("MainWindow", "Resetear"))
        self.bt_4.setText(_translate("MainWindow", "Instrucciones"))
        self.label_16.setText(_translate("MainWindow", "Despues de modificado el"))
        self.label_18.setText(_translate("MainWindow", "Excel, introduzca el numero de"))
        self.label_19.setText(_translate("MainWindow", "pasos"))
        self.bt_aceptar_manual.setText(_translate("MainWindow", "Aceptar"))
        self.bt_rutina1.setText(_translate("MainWindow", "Slantedpost"))
        self.bt_rutina2.setText(_translate("MainWindow", "Vertical post"))
        self.bt_rutina3.setText(_translate("MainWindow", "Chevron"))
        self.bt_rutina4.setText(_translate("MainWindow", "Slanted post stack"))
        self.bt_rutina5.setText(_translate("MainWindow", "Bragg stack"))
        self.bt_angulo0.setText(_translate("MainWindow", "Angulo a 0"))
        self.bt_rpm0.setText(_translate("MainWindow", "RPM a 0"))
        self.bt_tiempo0.setText(_translate("MainWindow", "Reiniciar tiempo"))
        self.label_15.setText(_translate("MainWindow", "-Intrucciones"))
        self.label_6.setText(_translate("MainWindow", "Glad"))
        self.label_7.setText(_translate("MainWindow", "Intrucciones"))
        self.label_8.setText(_translate("MainWindow", "-revisar que el sistema este    "))
        self.label_9.setText(_translate("MainWindow", "conectado correctamente"))
        self.label_10.setText(_translate("MainWindow", "-Angulos en grados"))
        self.label_11.setText(_translate("MainWindow", "Verificar si la rutina es en"))
        self.label_12.setText(_translate("MainWindow", "grados o rpm"))
        self.label_13.setText(_translate("MainWindow", "-Tiempos en minutos"))
        self.label_14.setText(_translate("MainWindow", "-Gracias por sus cuidados"))
        self.label_2.setText(_translate("MainWindow", "Introduzca el "))
        self.label_17.setText(_translate("MainWindow", "Tiempo"))
        self.bt_aceptar_R1.setText(_translate("MainWindow", "Aceptar"))
        self.bt_detener_R1.setText(_translate("MainWindow", "Detener"))
